### ISSUE TITLE
Cannot load class from dll

### ISSUE THREAD

**Issue by anandbadrinath-classes** [tr8dr/.Net-Bridge#10]
I have installed the package and dependencies and am attempting to import a custom DLL however I get the following error when attempting to import it. 
I would like to know if I am doing something wrong or if this is a known bug.

```
Traceback (most recent call last):
  File ".\test.py", line 10, in <module>
    printer = clr.new("Printer.Printer")
  File "D:\test\.Net-Bridge\venv\lib\site-packages\pydotnet\clr\CLRApi.py", line 123, in new
    return rep.toValue()
  File "D:\test\.Net-Bridge\venv\lib\site-packages\pydotnet\clr\data\CLRException.py", line 56, in toValue
    raise Exception (self.value)
Exception: System.ArgumentException: could not find type: Printer.Printer
   ? bridge.common.reflection.Creator.NewInstanceByName(String typename, Object[] args) dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 16939
   ? bridge.embedded.CLRBridgeEmbedded.Create(String classname, Object[] parameters) dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 84
   ? bridge.server.CLRBridgeServerClient.HandleCreate(CLRCreateMessage req) dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 1057
WARN  [2020-05-29 09:36:27.904]: receipt of messsage failed: System.IO.EndOfStreamException: End of stream reached with 1 byte left to read
   à bridge.common.io.SameEndianReader.InternalReadByte() dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 10400
   à bridge.common.io.SameEndianReader.ReadUInt16() dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 10221
   à bridge.server.CLRMessage.Read(IBinaryReader stream) dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 1422
   à bridge.server.CLRBridgeServerClient.Service() dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 980, stack:    à bridge.common.io.SameEndianReader.InternalReadByte() dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 10400
   à bridge.common.io.SameEndianReader.ReadUInt16() dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 10221
   à bridge.server.CLRMessage.Read(IBinaryReader stream) dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 1422
   à bridge.server.CLRBridgeServerClient.Service() dans d:\test\.Net-Bridge\src\Python\pyDotNet\server\Library.cs:ligne 980
```

Here is the C# file used to generate the dll

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Printer
{
    public class Printer
    {
        public void Print(string text)
        {
            Console.WriteLine(text);
        }
    }
}
```

And here is the python code I am using to import it

```
import os
virtual_env = os.environ['VIRTUAL_ENV']

print(f"Venv:{virtual_env}")

from pydotnet.clr.CLRApi import CLRApi

clr = CLRApi(hostname="localhost", dll="Printer.dll")

printer = clr.new("Printer.Printer")
printer.Print("HelloWorld!")
```

Given that I am using a virtualenv I also had to modifiy CLRApi.py l.77 like so
`server = "%s/Lib/site-packages/pydotnet/server/CLRServer.exe" % os.environ["VIRTUAL_ENV"]`

I am on Windows 10 using python3.6.8

This is the dll file generated 
[Printer.zip](https://github.com/tr8dr/.Net-Bridge/files/4702436/Printer.zip)

**Comment by tr8dr** [comment]
I am sorry, I have not had time to maintain this package and no longer using .NET, but if you cannot solve I can give it a go.   Have you tried running the CLRServer in visual studio and set a breakpoint in the main function to see whether the DLL is loading and another breakpoint at bridge.common.reflection.Creator.NewInstanceByName.  I am wondering whether your DLL did not load and was silently ignored.

**Comment by anandbadrinath-classes** [comment]
I found the bug, the -dll argument was never passed when the server was started.

If I make a pull request, could you approve it? Or would you prefer that I simply for the project?

**Comment by tr8dr** [comment]
yes, thank you.
